### ISSUE TITLE
Original Shield Driver for Inspiration

### ISSUE THREAD

**Issue by cpereirasp** [Greg-MM/C4-AndroidTV#1]
Hi @Greg-MM,

I have uploaded the original unencrypted Shield driver if you need some inspiration for the mini driver functionality. 
Couldn't find a better way to get this to you - so feel free to delete the issue later.

Hope it helps.

Great work so far btw! It's an amazing driver... I'm glad you made it open source.

[nv_shield.zip](https://github.com/Greg-MM/C4-AndroidTV/files/9259915/nv_shield.zip)

**Comment by Greg-MM** [comment]
Thanks
